GHC 7.10 added to Travis CI.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,1 +1,54 @@
 language: haskell
+
+matrix:
+  allow_failures:
+    - env: GHCVER=head
+    - env: GHCVER=7.4.2
+
+env:
+ - GHCVER=head
+ - GHCVER=7.10.1
+ - GHCVER=7.8.3
+ - GHCVER=7.6.3
+ - GHCVER=7.4.2
+
+before_install:
+ - sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER
+ - export PATH=/opt/ghc/$GHCVER/bin:$PATH
+
+install:
+ - travis_retry cabal-1.18 install --only-dependencies --force-reinstalls
+
+#script:
+# - bash testit.sh
+# - echo "All done."
+
+script:
+ # -v2 provides useful information for debugging
+ - cabal configure --enable-tests --enable-benchmarks -v2
+
+ # this builds all libraries and executables
+ # (including tests/benchmarks)
+ - cabal build
+
+ - cabal test
+
+ - bash testit.sh
+ - echo "Unit tests successful!"
+
+ - cabal check
+
+ # tests that a source-distribution can be generated
+ - cabal sdist
+
+ # check that the generated source-distribution can be built & installed
+ - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
